[package]
name = "rtc"
version = "0.1.2"
edition = "2024"
description = "Rust Text Calculator"
readme = "README.md"
repository = "https://github.com/kda/rtc"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
crossterm = "0.29.0"
log = "0.4.34"
pulldown-cmark = "0.13.4"
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
simplelog = "0.12.2"
strum = "0.28.0"
strum_macros = "0.28.0"
tempfile = "3.27.0"
yaml_serde = "0.10.7"

[dev-dependencies]
insta = "1.48.0"
